name: Uptake
favicon: null
layout_spectrum: 0.51902
typography_spectrum: 0.52364
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#19bef0'
    - '#0b5eaa'
    - '#000000'
    - '#00ffff'
    - '#0000ff'
  brandStrength: 0.5625
  lightness: 0
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
