name: Uptake
favicon: null
layout_spectrum: 0.5780166597105563
typography_spectrum: 0.03477906156331301
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6007265981752425
  lightness: 0.02595361741259694
  saturation: 0.16805048496462405
  rhythmicContrast: 0.6943208200391382
purpose: []
